version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
    command: gunicorn grandmas_cookbook.wsgi:application --bind 0.0.0.0:8000 --reload
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_started
    