version: '3.8'

services:
  web:
    build:
      context: .
    command: gunicorn grandmas_cookbook.wsgi:application --bind 0.0.0.0:8000 --reload
    ports:
      - 8000:8000
    volumes:
      - .:/code
    