# Generated by Django 4.2 on 2023-04-24 17:25

from django.db import migrations
from django.contrib.auth import get_user_model

User = get_user_model()

def populate_user(apps, schema_editor):
    User.objects.create_superuser("admin@mail.com", "admin", type="G")
    User.objects.create_user("golden@mail.com", "golden", type="G")
    User.objects.create_user("silver@mail.com", "silver", type="S")
    User.objects.create_user("bronze@mail.com", "bronze", type="B")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_user)
    ]
